### ISSUE TITLE
Workflow clarification

### ISSUE THREAD

**Issue by cb-anomitromunshi** [github/lock#15]
Hi, 
I want to clarify if this workflow will help my scenario.

Scenario:
I want to lock branch (staging) so that no one can merge any PR to staging. Following that i should be allowed to create a PR of staging against MAIN branch.

Can it be done through this action?

Thank you.
Appreciate your work.

**Comment by GrantBirki** [comment]
@cb-anomitromunshi Yes you absolutely can and in a variety of ways as well!

For example, if you use the following workflow, you can lock by using comments on pull requests:

```yaml
name: lock-or-unlock

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  lock-or-unlock:
    if: ${{ github.event.issue.pull_request }} # only run on pull request comments
    runs-on: ubuntu-latest
    steps:
      # Lock or Unlock via a comment (ex: .lock or .unlock)
      - uses: github/lock@vX.X.X # <--- the latest version of this Action
        id: lock
```

Commenting `.lock staging` will lock the `staging` environment on a pull request.
