### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by antipalindrome** [github/lock#17]
Can this be used without branch-deploy? 

I'm looking for a solution that would trigger a workflow through the CLI that locks a branch so that other people don't merge PRs into that branch while preparing for a deploy or while a deploy is ongoing.

Like I'd run a command in CLI that does the following:
1. It locks `main`
2. Runs the deploy
3. Unlocks `main`

**Comment by GrantBirki** [comment]
You sure can! The `lock` Action is pretty flexible as to how it can be used. You can "create" a lock in any fashion you like. You can create one from a CI run during a deployment, manually via a workflow dispatch, or via an IssueOps command like `.lock` (you can find all these details in the readme).

Here is an example of creating a lock during a CI run of a "deploy" and then unlocking when that deployment completes

```yaml
name: deploy

on:
  push:
    branches:
      - main

jobs:
  # create a "lock"
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-lock
        uses: github/lock@v2.0.1
        with:
          mode: "lock"
          reason: "preventing merges because we will be deploying soon"
          environment: "production"

  # Run the deployment pipeline
  deploy:
    needs: lock # wait for the lock job to finish
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        runs: echo "I'm deploying!" # replace with your actual deployment here

  # unlock the deployment pipeline
  unlock:
    needs: deploy # wait for the deploy job to finish
    runs-on: ubuntu-latest
    steps:
      - name: deploy-lock
        uses: github/lock@v2.0.1
        with:
          mode: "unlock"
          environment: "production"
```

The workflow linked above, does exactly what you are looking for (I believe). It creates a deployment lock for the `production` environment (this is likely `main` in your case), runs the deployment (you'll do this as you like), then it unlocks `production` so that other deploys can go through
