### ISSUE TITLE
`mode: "check"` flag to only check if a lock exists

### ISSUE THREAD

**Issue by GrantBirki** [github/lock#5]
# Check Lock 🔒 

This issue is for tracking work related to [environment specific locks](https://github.com/github/branch-deploy/issues/74) which was an issue opened in the primary [`branch-deploy`](https://github.com/github/branch-deploy) repository

This Action should be able to take an option like the one defined below to simply check if a lock exists without doing any additional actions.

```yaml
- uses: github/lock@vX.X.X
   id: lock
   with:
       mode: "check" # ⭐ (new!) rather than just having "lock/unlock" we should add a "check" option
```

---

This feature was suggested by @necropolina via https://github.com/github/branch-deploy/issues/74 - Thanks! ❤️
